-- Demo schema for the static admin page in web/admin.html.
-- This is intentionally permissive for local testing. Do not use these
-- policies unchanged for a real production admin surface.

create table if not exists public.flights (
    id bigint generated by default as identity primary key,
    airline text not null,
    flight_no text not null unique,
    origin text not null,
    destination text not null,
    depart_at timestamptz not null,
    arrive_at timestamptz not null,
    price numeric(10, 2) not null check (price >= 0),
    seats_available integer not null check (seats_available >= 0),
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.flights enable row level security;

drop policy if exists "Demo public select flights" on public.flights;
create policy "Demo public select flights"
    on public.flights
    for select
    to anon
    using (true);

drop policy if exists "Demo public insert flights" on public.flights;
create policy "Demo public insert flights"
    on public.flights
    for insert
    to anon
    with check (true);

drop policy if exists "Demo public update flights" on public.flights;
create policy "Demo public update flights"
    on public.flights
    for update
    to anon
    using (true)
    with check (true);

drop policy if exists "Demo public delete flights" on public.flights;
create policy "Demo public delete flights"
    on public.flights
    for delete
    to anon
    using (true);

insert into public.flights (
    airline,
    flight_no,
    origin,
    destination,
    depart_at,
    arrive_at,
    price,
    seats_available
)
values
    ('Pacific Horizon', 'PH218', 'LAX', 'NRT', '2026-04-14T08:10:00Z', '2026-04-14T19:45:00Z', 784.50, 31),
    ('Atlas Skies', 'AS552', 'SFO', 'LHR', '2026-04-18T16:05:00Z', '2026-04-19T06:30:00Z', 912.00, 18),
    ('North Star Air', 'NS144', 'SEA', 'ICN', '2026-04-20T11:25:00Z', '2026-04-21T01:50:00Z', 688.75, 24)
on conflict (flight_no) do nothing;
